language: julia
codecov: true
julia:
  - nightly
  - 1.0
  - 1
notifications:
  email: false
before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="MathOptInterface", rev="bl/cache_constrained_variables"))'
